### ISSUE TITLE
Delayed::DeserializationError: Job failed to load: undefined method `engine' for nil:NilClass.

### ISSUE THREAD

**Issue by rmatesic** [collectiveidea/delayed_job_active_record#101]
Not sure if this is a bug with delayed_job_active_record but I just wanted to run it with others who may be getting this issue.

I have a UserMailer class which accepts a user and a collection of products and I perform this method with delayed jobs like below.

      UserMailer.delay.send_products_update_notification(user, my_products)

For some weird reason when my_products is an ActiveRecord::Relation::ActiveRecord_Relation_Product by doing my_products.class I receive the following error when my job is being run.

      Delayed::DeserializationError: Job failed to load: undefined method `engine' for nil:NilClass.

But as soon as I change my mailer by converting my_products to an array my task works.

       UserMailer.delay.send_products_update_notification(user, my_products.to_a)

Not sure if I am doing something wrong here of that it's a known issue with the gem. If anyone has any insight as to why this could be happening, that would be helpful. Thanks.

**Comment by betamatt** [comment]
Yeah, don't do that :) There's all kinds of objects that DJ can't reliably serialize and blindly using `delay` on arbitrary object types is dangerous.

Best practice is to call delay with the ids of the objects and refetch them in the job. This way you're not serializing some huge object graph and always get the freshest version of the data. Ex: `UserMailer.delay.send_products_update_update_notification(user.id, my_products.pluck(:id))`

**Comment by snmmaurya** [comment]
betamatt is right, do not pass the my_products, pass its reference in the form of singular object as (variable or array) by which you could retrieve appropriate products.
