### ISSUE TITLE
Rails 5 support

### ISSUE THREAD

**Issue by pwnall** [collectiveidea/delayed_job_active_record#109]
Please consider removing the Rails 5 restriction from the gemspec, so folks who want to live on the bleeding edge, like me, can use `delayed_job` in our projects.

I tried removing the restriction, and things seem to work fine for me.
https://github.com/pwnall/delayed_job_active_record/tree/rails5

Thank you for delayed_job! :heart:

**Comment by albus522** [comment]
We won't be removing the upper limit on the release gem, although I am considering creating an edge branch that you could track to if you want to live dangerously.

**Comment by mvastola** [comment]
+1

**Comment by mvastola** [comment]
I would just like to add that with the release of Rails 5.0.0.beta1 just days ago, many users (myself included) are seeking to upgrade their current Rails 4.2 apps to ensure forward-compatibility with this new version of Rails and to make use of its new features and capabilities. This is difficult to do visavis  delayed_job with AR until this change is made.

**Comment by mvastola** [comment]
Please note I have submitted PR #118 which enables compatibility with Rails 5.0.x and runs it against the provided battery of CI tests, confirming that all integration tests pass with this newest version of Rails.

I would therefore propose that this gem is ready for release with Rails 5.0.x interoperability supported.

**Comment by Wolfe13** [comment]
+1

**Comment by mvastola** [comment]
@albus522 Thanks for merging! Any chance of pushing out a new release to encourage testing of Rails 5 since it's now in beta?

**Comment by albus522** [comment]
Right now there are still deprecation warnings, so not ready for a release. Also not likely to cut an official release until there is at least an rc version of rails. In the meantime you can use bundler's git handling http://bundler.io/git.html

**Comment by mvastola** [comment]
@albus522 I can submit a patch for the one remaining deprecation warning tonight. Should be really simple. Unfortunately there wasn't a backwards-compatible replacement IIRC.

**Comment by albus522** [comment]
Yeah. We can't just remove the offending code. It should work across the board.

**Comment by mvastola** [comment]
@albus522 
FYI, the only deprecation warning I can see is for an invocation of `alias_method_chain` triggered by [calling `handle_asynchronously` here](https://github.com/collectiveidea/delayed_job_active_record/blob/eafc9c21c0b347a8bfca838797294f9b45f2fdcc/spec/helper.rb#L62).

`handle_asynchronously` which is actually [defined here](https://github.com/collectiveidea/delayed_job/blob/2014009496dd0b2af217ab322f74f91fe4e26097/lib/delayed/message_sending.rb#L31),  in the `delayed_job` repo, and the deprecation seems to be resolved in the master branch of said repo (and, I suppose, simply hasn't been pushed out in a release), so there actually isn't anything to be patched.

Please let me know if there were any other deprecations warnings you caught that are in need of attention.


Also, out of curiosity, what is your philosophy regarding waiting for an RC to enable Rails 5 support? I'm familiar with bundler's ability to point to git repos, but my perpetual concern with that is one has to either:
a) lock the gem to a particular commit and thereby sacrifice automatic updates when important changes/fixes are released, or;
b) not lock the gem to a particular commit and thereby risk stability if a breaking commit should be committed to the branch

**Comment by mvastola** [comment]
Hi @albus522, just a gentle ping as I haven't heard back to my most recent comment.

**Comment by albus522** [comment]
Things in rails are not considered stable until at least an RC. If we enable rails 5 support and then something breaks there is no way to change the version dependencies after the fact. We have decided to take the cautious approach because we have been bitten by lax dependency requirements too often.

**Comment by mvastola** [comment]
Ah. To me, if something breaks,  no one has a right to complain (especially to you) as they they gave that right up when choosing to use a pre-release gem (especially such an integral one). But I understand your predicament.. Something being common sense is no guarantee people will adhere to it.

I guess I'll hold off on nagging you until an RC then. :-)

Thanks again for all your help!

**Comment by rhymes** [comment]
@mvastola @albus522  Any news on this? Rails 5 is at the RC1 stage now.

Thanks!

**Comment by mvastola** [comment]
@rhymes I admit I had totally forgotten about this. @albus522's stated motive in waiting for an RC before pushing a new version of `delayed_job` was making sure that the Rails 5 code base didn't change such that `delayed_job`'s compatibility with Rails 5 would be broken after a Rails 5-compatible `delayed_job` had been officially released.

So -- barring a misunderstanding on my part of @albus522's plan -- presumably this gem is good for a release now, assuming its CI tests are passing against the Rails 5 RC (and perhaps Edge Rails for good measure). 

I don't have time to do this now, but running the tests should be fairly straightforward if anyone else wants to give it a go. 

If any errors/bugs crop up, feel free to let me know and I'm happy to submit a PR if no one beats me to it!

**Comment by Plummat** [comment]
So, rails 5 is out now.... any timeline?

**Comment by mvastola** [comment]
FWIW, all the latest CI checks on [`delayed_job`](https://travis-ci.org/collectiveidea/delayed_job) and [`delayed_job_active_record`](https://travis-ci.org/collectiveidea/delayed_job_active_record) are passing when it comes to `gem 'rails', '~> 5.0.x'` and compatible ruby engines.

**Comment by albus522** [comment]
It has for a month and a half.

**Comment by albus522** [comment]
https://rubygems.org/gems/delayed_job_active_record

**Comment by gonuguntla** [comment]
Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    lograge was resolved to 0.11.2, which depends on
      actionpack (>= 4)

    rails (= 6.1.0) was resolved to 6.1.0, which depends on
      actionpack (= 6.1.0)
Please anyone help me how to resolve it
