### ISSUE TITLE
Can I share only one delayed job table within two different projects

### ISSUE THREAD

**Issue by Martin288** [collectiveidea/delayed_job_active_record#110]
Hello guys, I currently have two different rails projects, let us name it Pro1 and Pro2. They both connect to the same database, and Pro1 has all database migration files, while Pro2 doesn't have any migration. I tried to share the database between these two projects with delayed_job, but it seems like that Pro1 might run jobs which are from Pro2. I now have a solution that force Delayed::Backend::ActiveRecord::Job.table_name to something else in Pro2, so Pro1 and Pro2 will both have independent tables. Do you have any better solutions? Thanks in advance!

**Comment by albus522** [comment]
Using queues would be your only other option and setting a queue for each project. Sharing a database with multiple projects is generally just a bad idea. There are just too many things that can go wrong.
