### ISSUE TITLE
Customized attr_accessible

### ISSUE THREAD

**Issue by alkuzad** [collectiveidea/delayed_job_active_record#115]
Hi

I want to develop plugin which will require additonall data to be passed on delay / handle_asynchronously wrapper. Currently attr_accessible is blocking that as the newly added option will not be passed to object.

Do you mind changing attr_accessible to attr_protected ? This should look like this:

`attr_protected :id, :attempts, :last_error, :created_at, :updated_at`

**Comment by alkuzad** [comment]
I figured out how to change the behaviour with alias_method_chain (https://gist.github.com/alkuzad/54ee23780c436e57f116) but still - is it right for application that is intended to be extended via plugins to use `attr_accessible` instead of just protecting the needed variables ?

**Comment by betamatt** [comment]
I'd prefer to maintain a whitelist using `attr_accessible`. You'll have to patch the Job class to whitelist the additional attribute.
