### ISSUE TITLE
Loading the gem triggers a connection attempt to the DB

### ISSUE THREAD

**Issue by moritzschepp** [collectiveidea/delayed_job_active_record#122]
So when I add it to the Gemfile, I can no longer run assets:precompile without having a configured database. I can workaround with

    gem 'delayed_job_active_record', require: false

and then in an initializer:

    unless Rails.groups.include?(:assets)
      require 'delayed_job_active_record'
    end

But that's not optimal.

**Comment by albus522** [comment]
We do not have a way to not trigger ActiveRecords loading code on app startup. So your non-optimal solution is about all you can do. Also not having access to the db while compiling assets is pretty rare. I have heard of it happening before, but it is never easy.

**Comment by moritzschepp** [comment]
Just to name the use case: We are building docker containers for CI and production. The db naturally sits in a different container than the assets and on build time they can't be connected yet.

So there is

    ActiveSupport.on_load :active_record do
      ...
    end

Could that not be used to load the delayed_job_active_record code? This way it would only be loaded if activerecord itself is.

**Comment by albus522** [comment]
No it can't, as that may never get triggered.

**Comment by moritzschepp** [comment]
Alright, in any case: Thanks a lot!

**Comment by albus522** [comment]
I wish I had a better answer, but unfortunately it is complicated.

**Comment by moritzschepp** [comment]
I completely understand. Also I see part of the solution in rails since there is currently no way to prevent certain gems from loading during assets:precompile (which always loads at least the `default` group). In rails 3, there was still the `asset` group.
