### ISSUE TITLE
Issue for Rails delayed_job + SQL server

### ISSUE THREAD

**Issue by pvijayror** [collectiveidea/delayed_job_active_record#126]
I am trying to download jobs in local tmp directory. If we use mysql server working fine. but why sql sever not working delayed job ... Even not able to fined any logs or errors

dashboard controller

def call_csv
#job = ProjectJob.new(options).delay.perform 
job = Delayed::Job.enqueue(ProjectJob.new(options))
flash[:notice] = "Your Report Download Request has been taken. Please check - My Downloads"
redirect_to :back 
end

apps/jobs/project_job.rb

class ProjectJob < Struct.new(:options) 
p ">>>>>>>>>>> ProjectJob" 
def perform
file_name = options[:file_name]

require 'csv'

dir = "#{Rails.root}/tmp"
Dir.mkdir(dir) unless File.exists? dir
file = "#{Rails.root}/tmp/#{file_name}.csv"
CSV.open(file, "w") do |csv|
.....
end
puts "Job end... #{column_type}"
$is_completed = true
end
end

def after(job)
puts "Job completed... #{$is_completed}"
if $is_completed
p "job completed........."
$is_completed = nil
end

end
handle_asynchronously :perform 
end

database.yml

development:
adapter: sqlserver 
host: localhost 
port: 15551
username: 
password: xxx 
database: timeout: 0

Please let me know if any configuration required for sqlserver database or is it support sqlserver database with delayed job?

**Comment by albus522** [comment]
Duplicate https://github.com/collectiveidea/delayed_job/issues/921
