### ISSUE TITLE
releasing DB connection back to pool

### ISSUE THREAD

**Issue by abiacco** [collectiveidea/delayed_job_active_record#127]
I hope this is the right place to ask this.
I'm running DJ 4.1.2, DJR 0.3.5, DJAR 4.1.1, AR 4.2.6. 

I have noticed what i believe is DJ not releasing the DB connection that it has back to the pool after an operation.

I notice this when:
1) My UPDATE sql command runs (e.g. UPDATE `delayed_jobs` SET `delayed_jobs`.`locked_at` ...) every sleep_delay seconds.
2) after a long-running job

If for some reason the connection gets severed, like the mysql server goes down between UPDATEs or a job takes longer than the wait/interactive timeout in mysql, the next query will come back with "Communications link failure".

Is this normal? And if so, is there a reason for it? I'd rather it not hold onto the connection which may or may not still be there.

Thanks,

-Tony

**Comment by albus522** [comment]
This actually has nothing to do with the connection pool. AR does very little to try to maintain an existing connection. We have a retry loop wrapped around the job reservation code https://github.com/collectiveidea/delayed_job/blob/master/lib/delayed/worker.rb#L309 but there is nothing we can do for db failures within the job. You may need to tweak the settings on your database server to allow longer connections.

**Comment by abiacco** [comment]
For the job, increasing the timeout is what i ended up having to do. It seems like it had a problem at the end of the job when it was trying to do the INSERT and DELETE combo.
For the UPDATEs, i don't know.
I am testing out, in lib/delayed/backend/active_record.rb, not doing the establish_connection in after_fork and just in clear_locks/reserve_with_scope_using_optimized_sql doing the establish_connection before the query and clear_all_connections after, and that works better.
May not be worth the effort.
Thanks.

**Comment by albus522** [comment]
That means you are disconnecting and reconnecting to the database before you do anything. That isn't really a solution. If you actually need to do that, there is something seriously wrong with your database server.

**Comment by abiacco** [comment]
Under normal circumstances, it's fine. But when the connection is severed, like when the database server goes down/restarts, the query will fail since it's still checked out. With a pool behind it, it would be checking out from the pool and then checking back in. I'm just not sure a connection should be checked out for the life of the process.

**Comment by albus522** [comment]
I think you might be confused on how the AR connection pool works. The AR connection pool does not disconnect checked in connections. And DJ does not check out or check in a connection, AR does when you use it.

**Comment by abiacco** [comment]
nono, i'm not saying it's disconnecting it.
DJAR is checking out a connection from the pool when it does the establish_connection in the after_fork, "borrowing" if you will, unless i'm not understanding the code correctly.
But then it doesn't get checked back into the pool again when it's finished with it.
Pretty sure best practice, in any language, is to check out a connection, use it, then release it back to the pool. Otherwise it would be considered abandoned.

**Comment by albus522** [comment]
`establish_connection` sets up the pool not an individual connection in the pool https://github.com/rails/rails/blob/107f4282bbfabc011d5ad3bcf3fb3c6fb812ad30/activerecord/lib/active_record/connection_adapters/abstract/connection_pool.rb#L536

**Comment by albus522** [comment]
To further explain, the `establish_connection` code you are referencing only runs if you use `bin/delayed_job start`. This is because an initial process starts up in which rails might automatically establish a connection during boot. The "might" and how is highly dependent on the rails version and app specifics. So we make sure we don't accidentally share a connection across multiple processes by manually disconnecting before we fork off the individual worker processes. Because we manually disconnected, we need to tell each of the newly forked processes to reconnect. This is what `establish_connection` does. The connection pool makes it so the potential for accidentally sharing a connection is less likely but sometimes things get weird, so we play it safe.

None of this matters if you run DJ using `bin/delayed_job run`, `rake jobs:work`, or `rake jobs:workoff` as these don't fork, so they don't run this code.

**Comment by abiacco** [comment]
That being true then AR is implicitly checking out for you automatically on an AR operation and isn't smart enough to know when the connection behind it goes away, as you said earlier. Well crap. I guess the only way around the braindeadness of this would be to use checkout()/checkin() or to use with_connection.

**Comment by abiacco** [comment]
Yeah, i'm using DJ inside a jruby-rack-worker

**Comment by albus522** [comment]
You probably need to move your issue there. As jruby is incapable of using fork, there is no reason they should be using the fork callbacks.

**Comment by abiacco** [comment]
Yes yes, of course.
I can tell you though, just for potential future reference, that it does run the before_fork and after_fork, as i added logging in there. The jruby rack worker starts up a separate java thread and then runs DJ inside of that.
I remembered reading this [https://bibwild.wordpress.com/2014/07/17/activerecord-concurrency-in-rails4-avoid-leaked-connections/](url) which made me think about the checkin/out thing in threads.

But anyways, thanks for taking the time!

**Comment by albus522** [comment]
I know jruby-rack-worker does use the fork callbacks, I looked up the library after you mentioned it, but it shouldn't. It would also need to implement any special connection handling as that isn't generally needed for any of the supported methods of running DJ. Hopefully the information here helps you get to the changes that need to be made.
