### ISSUE TITLE
Update to support Rails 5.1

### ISSUE THREAD

**Issue by rubys** [collectiveidea/delayed_job_active_record#137]
https://rubygems.org/gems/delayed_job_active_record/versions/4.1.1 specifies activerecord < 5.1, >= 3.0 

https://github.com/rails/rails/blob/5-1-stable/Gemfile#L71 optionally pulls in delayed_job_active_record

**Comment by md5** [comment]
Looks like #134 aims to address this.

**Comment by laserlemon** [comment]
Yes, #134 is the better place to have this conversation. Thank you!
