### ISSUE TITLE
bundler could not find compatible versions for gem 'activerecord'

### ISSUE THREAD

**Issue by webmaster219** [collectiveidea/delayed_job_active_record#140]
rails version is 5.1.1
activerecord version is 5.1.1
How can I use this gem in rails 5.1.1 project?

**Comment by maurosbu** [comment]
It is not possible at the moment.

**Comment by MaicolBen** [comment]
I thought this wasn't resolved, but yes, there is a release 4.1.2 that covers rails 5.1.2

**Comment by albus522** [comment]
Yeah. We didn't do a very good job cleaning up all the random issues after the last release
