### ISSUE TITLE
without requiring DJ ~> 4.1.4, gem cannot be loaded in ruby 2.5

### ISSUE THREAD

**Issue by apurvis** [collectiveidea/delayed_job_active_record#145]
See https://github.com/collectiveidea/delayed_job/pull/996

without explicitly requiring delayed_job ~> 4.1.4 in `Gemfile`, ruby 2.5 cannot load this gem.  error:
```
$ bx rails c
~/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/bundler-1.16.1/lib/bundler/runtime.rb:84:in `rescue in block (2 levels) in require': There was an error while trying to load the gem 'delayed_job_active_record'.
Gem Load Error is: undefined method `yaml_as' for ActiveRecord::Base:Class
Did you mean?  yaml_tag
```

**Comment by albus522** [comment]
Repo tagging does not cause this issue. That error is simply telling you that you didn't update after updating to ruby 2.5.0.

**Comment by apurvis** [comment]
i didn't say that repo tagging had anything to do with it; i was more suggesting that there be a version of this gem that requires DJ over version 4.1.4 so that it doesn't break when installed on ruby 2.5

**Comment by albus522** [comment]
No, the version requirement here should not be that high, because everything works just fine for everything but ruby 2.5.0. All you had to do was run `bundle update` or a more specific `bundle update delayed_job` which is pretty much expected when upgrading ruby.
