### ISSUE TITLE
Out dated active record dependency

### ISSUE THREAD

**Issue by mode-x** [collectiveidea/delayed_job_active_record#155]
There seems to be an issues with the version of active record for the gem when upgrading to Rails 5.2.0. Is there any fix for this? Below is the error:
`In Gemfile:
delayed_job_active_record (>= 4.1.2, ~> 4.1) was resolved to 4.1.2, which
depends on
      activerecord (< 5.2, >= 3.0)
    rails (= 5.2.0) was resolved to 5.2.0, which depends on
      activerecord (= 5.2.0)`

**Comment by ErCollao** [comment]
Same issue here!

**Comment by FanaHOVA** [comment]
#154

**Comment by albus522** [comment]
New release is out
