### ISSUE TITLE
Rails 6.0.0 beta1 activerecord compatibility issues

### ISSUE THREAD

**Issue by atstockland** [collectiveidea/delayed_job_active_record#164]
When upgrading rails to 6 beta 1, bundler finds a compatibility issue between delayed_job_active_record and activerecord constraint.

Bundler could not find compatible versions for gem "activerecord":
  In snapshot (Gemfile.lock):
    activerecord (= 6.0.0.beta1)

  In Gemfile:
    delayed_job_active_record (~> 4.1, >= 4.1.3) was resolved to 4.1.3, which depends on
      activerecord (>= 3.0, < 5.3)

**Comment by albus522** [comment]
There are beta versions of both delayed_job and delayed_job_active_record out now with rails 6 support
