### ISSUE TITLE
Rails 6.1.0.alpha support

### ISSUE THREAD

**Issue by max611** [collectiveidea/delayed_job_active_record#178]
When upgrading to Rails 6.0.1.alpha, I get the following error:

```
delayed_job_active_record was resolved to 4.1.4, which depends on
      delayed_job (>= 3.0, < 5) was resolved to 4.1.8, which depends on
        activesupport (>= 3.0, < 6.1)
```

Would you allow the modification of the gemspec to `spec.add_dependency "activerecord", [">= 3.0", "< 6.2"]` Seems like this is something that was asked [in the past](https://github.com/collectiveidea/delayed_job_active_record/issues/109) so I wanted to ask before. Otherwise, I can create a PR to update CI tests and add `Rails 6.1.0.alpha`

**Comment by nehresma** [comment]
This is going to be important with the release of Rails 6.1 this week.

**Comment by albus522** [comment]
Release is out.

**Comment by nehresma** [comment]
Thank you @albus522 !!
