### ISSUE TITLE
4.1.5 breaking changes

### ISSUE THREAD

**Issue by estani** [collectiveidea/delayed_job_active_record#188]
4.1.5 seem to have much more changes than the micros version bump.

I have to confess I had to patch `Delayed::Backend::ActiveRecord::Job` in order for it to work with apartment (so this is not a complaint, it's more of an info request :)

Excerpt of the problematic patch:
```
class Delayed::Backend::ActiveRecord::Job
  attr_accessor :apartment_schema

  class << self
    alias_method :__reserve_with_scope__, :reserve_with_scope

    #= Use Multi-Schema Job Selection if uses apartment
    def reserve_with_scope(ready_scope, worker, now)
      if Rails.application.config.use_apartment
        postgres_multischema_for_apartment(ready_scope, worker, now)
      else
        __reserve_with_scope__(ready_scope, worker, now)
      end
    end
```

The Problem:
```
/config/initializers/apartment.rb:193:in `alias_method': undefined method `reserve_with_scope' for class `#<Class:Delayed::Backend::ActiveRecord::Job>' (NameError)
```
If I understand the message correctly, ActiveRecord is there but either Job is not, or at least does not defined the method 'yet'.
I can't find what changed for this to not work anymore.

Background info about why the patch:
If using apartment, the next item to process will be searched for in `delayed_jobs` in multiple schemata, so all tenants are contained within schemas and there's only one delay_job backend strategy (might be more than one worker)

**Comment by jacobjlevine** [comment]
I've got a similar patch in place that's broken by the upgrade, so commenting here to follow along for more info.

**Comment by jacobjlevine** [comment]
@estani FYI, I was able to fix the issue using prepend + super. Originally I had an initializer that looked like this:

`module Delayed
    module Backend
      module ActiveRecord
        class Job
          class << self
            alias_method :reserve_original, :reserve
            def reserve(worker, max_run_time = Worker.max_run_time)
              previous_level = ::ActiveRecord::Base.logger.level
              ::ActiveRecord::Base.logger.level = Logger::WARN if previous_level < Logger::WARN
              value = reserve_original(worker, max_run_time)
              ::ActiveRecord::Base.logger.level = previous_level
              value
            end
          end
        end
      end
    end
  end`

The following change to that initializer file allowed for the same functionality to work with 4.1.5.

`module Delayed
  module Backend
    module ActiveRecord
      module Silencer
        def reserve(*args)
          previous_level = ::ActiveRecord::Base.logger.level
          ::ActiveRecord::Base.logger.level = Logger::WARN if previous_level < Logger::WARN
          value = super(*args)
          ::ActiveRecord::Base.logger.level = previous_level
          value
        end
      end

      class Job < ::ActiveRecord::Base
        class << self
          prepend Silencer
        end
      end
    end
  end
end`

**Comment by estani** [comment]
Interesting, would it be the same to just define Job as inheriting from active base?
I'll have to check this (I presume it won't work. We are patching the class, which we can't do before the class is loaded, otherwise our patch might be overridden by the original implementation...)
In the worst case I'll do similarly, storing the changes in a module and applying it after rails has beeing initialized.

**Comment by jacobjlevine** [comment]
I'm not 100% sure what's going on, but here's my tentative understanding. Previously, the Job class was getting defined by the gem first, then reopened and expanded in the initializer. It seems like you might not need to redeclare class inheritance when you're reopening a class. Now, however, the gem files aren't getting loaded until later, so your initializer code will run first. You'll need to inherit from ActiveRecord::Base in the initializer because now that's the primary class declaration. If you don't, you'll end up getting a superclass mismatch error once the gem loads.

Good luck!

**Comment by albus522** [comment]
https://github.com/collectiveidea/delayed_job_active_record/issues/185#issuecomment-808326919
Please reopen if that doesn't fix this
