### ISSUE TITLE
A way to get the job ID inside a worker?

### ISSUE THREAD

**Issue by LucasCioffi** [collectiveidea/delayed_job_active_record#189]
Hi All,

I noticed that [Sidekiq has a way](https://github.com/mperham/sidekiq/issues/1999) to get the job ID from within a worker.  

Is there something similar with DJ?
```
class MyWorker
  def perform(params)
    puts "starting #{self.job_id}"
    # work gets done
    puts "finishing #{self.job_id}"
  end
end
```

The goal is to be able to see if a worker finishes.  We're on Heroku and I think we are having some zombie "dynos" (servers) that get disconnected from our app before finishing their work.

Thank you!

**Comment by jdelStrother** [comment]
Perhaps a bit late for your use case, but you might try something like this to tag all your logs with the worker PID & job id: 

```ruby
module Delayed
  module Plugins
    class TaggedLogging < Delayed::Plugin
      Delayed::Worker.logger = Rails.logger

      callbacks do |lifecycle|
        lifecycle.around(:execute) do |worker, *args, &block|
          Rails.logger.tagged "Worker:#{$$}" do
            block.call(worker, *args)
          end
        end

        lifecycle.around(:invoke_job) do |job, *args, &block|
          Rails.logger.tagged "Job:#{job.id}" do
            block.call(job, *args)
          end
        end
      end
    end
  end
end
Delayed::Worker.plugins << Delayed::Plugins::TaggedLogging
```

**Comment by henrik** [comment]
I did this: https://github.com/mperham/sidekiq/issues/1999#issuecomment-1227065181

**Comment by LucasCioffi** [comment]
Thank you very much, @hrdwdmrbl and @jdelStrother.
