### ISSUE TITLE
Use `update` instead of `update_all` in the reserve_with_scope_using_optimized_mysql method.

### ISSUE THREAD

**Issue by M-Yamashita01** [collectiveidea/delayed_job_active_record#198]
Hello, I read the code in the `reserve_with_scope_using_optimized_mysql` method and found the following code.

https://github.com/collectiveidea/delayed_job_active_record/blob/d65b0f9900f5b0c78c341c7c0209c2d138d64ec5/lib/delayed/backend/active_record.rb#L148

We think that the return value of `ready_scope.limit(1)` is `ActiveRecord::Relation` and `ActiveRecord::Relation` has `update` method in addition to `update_all` method in Rails 3 and later.
In addition, the target record of `ready_scope.limit(1)` to be updated is only one record.

Therefore, we think you can use `update` instead of `update_all`.
Could you please tell me why you are using the `update_all method`?

Thank you.

**Comment by albus522** [comment]
`update_all` is a direct query method and intentional. `update` is an ActiveRecord compound operation with a lot of overhead we do not want.
