### ISSUE TITLE
Do that destroy_failed_jobs get honored by delayed_job?

### ISSUE THREAD

**Issue by vpereira** [collectiveidea/delayed_job_active_record#203]
Hi, I use in my application the `delayed_job_active_record` gem, that consequently uses `delayed_job`. I added to an initializer named `delayed_job.rb` the following line:

```
Delayed::Worker.destroy_failed_jobs = false
``` 

I check on my console if the variable is set to false, and indeed it is set to false.

I've got some new delayed job exceptions on my errbit instance. I was expecting to be able to introspect those jobs to see why they are broken. For my surprise they are not there:

Some Debug information:

```
Loading production environment (Rails 6.1.4)
[1] pry(main)> Delayed::Worker.destroy_failed_jobs
=> false
[2] pry(main)> Delayed::Job.where.not(failed_at: nil)
=> []
[3] pry(main)> Delayed::Job.where.not(last_error: nil)
=> []
[4] pry(main)> Delayed::Job.count
=> 9
[5] pry(main)> 

```

**Comment by albus522** [comment]
If the jobs succeed on retry, they are no longer failed. I would expect this is what happened.
