### ISSUE TITLE
Rails 7 weird error: can't dump anonymous module

### ISSUE THREAD

**Issue by gotchahn** [collectiveidea/delayed_job_active_record#206]
I upgraded my app to Rails 7 and had to upgrade:

- `delayed_job_active_record` (4.1.7)
- `delayed_job` (4.1.10)

I have a code similar than this: 

```ruby
# controller
class SomeController < ApplicationController
  def index
     respond_to do |format|
          format.csv do
             MyClass.export(args)
          end
     end
  end
end

# my class
class MyClass

  def self.export(args)
    Delayed::Job.enqueue new(args), queue: "slow"
  end
end
```

The code has been working fine until now that I get the error:

```
TypeError: can't dump anonymous module: #<Module:0x00007ff1823e84f8>
```
with the code `Delayed::Job.enqueue new(args)`  and with the first line in the full stack trace: 
```
ruby/2.7.0/psych/visitors/yaml_tree.rb:308:in `visit_Module'
```

What have changed? Thanks for the help.

**Comment by mwood** [comment]
Does "args" contain the controller "params" object?

If so I worked around a similar issue on Rails 7 by passing it in as "params.to_unsafe_h" .

**Comment by gotchahn** [comment]
Ha! Interesting @mwood , I did send the `params` object, so,  I ensure to use the permit-params method instead of using directly `params` and now is working! 

Thanks for the tip, I couldn't know that!

**Comment by gotchahn** [comment]
Closing this issue now, using permitted params avoid the error.
