### ISSUE TITLE
How does max_attempts interface with ActiveJob retry_on method?

### ISSUE THREAD

**Issue by jeremygottfried** [collectiveidea/delayed_job_active_record#210]
https://apidock.com/rails/v6.1.3.1/ActiveJob/Exceptions/ClassMethods/retry_on

The ActiveJob `retry_on` hook allows you to customize how you respond to specific errors, but it's unclear how that integrates with `max_attempts` in this gem. Does this gem keep a separate queue and ignore ActiveJob behavior, or is `max_attempts` just setting a global `retry_on` to catch all errors?

(sorry I made this issue on the main repo and then realized this would be a better place)

**Comment by albus522** [comment]
`retry_on` bypasses delayed_job. ActiveJob enqueues a new job and makes the original job look successful to DJ.

**Comment by hrdwdmrbl** [comment]
You can get `max_attempts` working by simply modifying the initializer for the job. I chose to do it for the parent class.

I do the same thing for `queue_name` and `max_run_time`

```
class ApplicationJob < ActiveJob::Base
  def initialize(*args, **kwargs, &block)
    super
    # Defaults
    @queue_name = queue_name
    @max_run_time = max_run_time
    @max_attempts = max_attempts
  end

  def max_run_time
    Delayed::Worker.max_run_time
  end

  def queue_name
    Delayed::Worker.default_queue_name
  end

  def max_attempts
    Delayed::Worker.max_attempts
  end
end
```

Your job class
```
class MyJob < ApplicationJob
  def max_attempts
    1
  end
end
```

**Comment by hrdwdmrbl** [comment]
Sorry, the above was actually wrong! I don't know how I thought that it worked. 

This is how you can actually do it:

First, put this in an initializer:

```
module ActiveJob
  module QueueAdapters
    class DelayedJobAdapter
      class JobWrapper
        def max_attempts
          job_data["job_class"].constantize.max_attempts || Delayed::Worker.max_attempts
        end

        def max_run_time
          job_data["job_class"].constantize.max_run_time || Delayed::Worker.max_run_time
        end
      end
    end
  end
end
```

Then you can set max_attempts and max_run_time as class methods on your jobs

```
class MyJob < ActiveJob::Base
  def self.max_attempts
    1
  end
end
```
