### ISSUE TITLE
Deprecation warning in rails 7.1

### ISSUE THREAD

**Issue by bjer** [collectiveidea/delayed_job_active_record#217]
Got a deprecation warning when updating an app to Rails 7.1:
```
 DEPRECATION WARNING: Calling `ActiveRecord::Base.clear_all_connections! is deprecated. 
Please call the method directly on the connection handler; for example: 
`ActiveRecord::Base.connection_handler.clear_all_connections!`. 
(called from before_fork at .rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/bundler/gems/delayed_job_active_record-6e8709f887fa/lib/delayed/backend/active_record.rb:65)
 (ActiveSupport::DeprecationException)
```
Fixed by changing call clear_all_connections! in active_record.rb:65

**Comment by ghiculescu** [comment]
@albus522 was this resolved? It seems to still be here: https://github.com/collectiveidea/delayed_job_active_record/blob/c7e7ceb10b7a50cf4de4e485fdef4581ad2c37e1/lib/delayed/backend/active_record.rb#L65

**Comment by ghiculescu** [comment]
FYI to anyone else - this was fixed in https://github.com/collectiveidea/delayed_job_active_record/pull/218
