### ISSUE TITLE
Does not work with PostgreSQL 8.4

### ISSUE THREAD

**Issue by duritong** [collectiveidea/delayed_job_active_record#33]
Although #32  fixed issues with PostgreSQL it still does not work with PostgreSQL 8.4, which for example ships with RHEL 6.

Error:
<code>
$ rake jobs:work --trace
[Worker(host:foo.localdomain pid:8232)] Starting job worker
rake aborted!
PG::Error: ERROR:  SELECT FOR UPDATE/SHARE is not allowed in subqueries
: UPDATE "delayed_jobs" SET locked_at = '2013-02-18 09:58:32.257303', locked_by = 'host:foo.localdomain pid:8232' WHERE id IN (SELECT  id FROM "delayed_jobs"  WHERE ((run_at <= '2013-02-18 09:58:32.207834' AND (locked_at IS NULL OR locked_at < '2013-02-18 07:58:32.207910') OR locked_by = 'host:foo.localdomain pid:8232') AND failed_at IS NULL) ORDER BY priority ASC, run_at ASC LIMIT 1 FOR UPDATE) RETURNING *
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1153:in `async_exec'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1153:in`exec_no_cache'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:662:in `exec_query'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:280:in`log'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activesupport-3.2.12/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract_adapter.rb:275:in`log'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:661:in `exec_query'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/connection_adapters/postgresql_adapter.rb:1248:in`select'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/database_statements.rb:18:in `select_all'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/connection_adapters/abstract/query_cache.rb:63:in`select_all'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/querying.rb:38:in `find_by_sql'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/explain.rb:33:in`logging_query_plan'
/home/duritong/.rvm/gems/ree-1.8.7-2012.02@enclouder/gems/activerecord-3.2.12/lib/active_record/querying.rb:37:in `find_by_sql'
</code>

I could not find any requirements regarding PostgreSQL Version. It would be good if you would support the latest database version on the latest major enterprise linux distribution.

**Comment by PatLeb** [comment]
There is a quick fix that works 13333911fc3266feba7f80b29f8bc3c642198e0f
